// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlDBkf7szFMDP9RoGOjwhKEUCKYmwDlQ',
    appId: '1:885423978672:web:3daf9831c55aae00aca375',
    messagingSenderId: '885423978672',
    projectId: 'masariweb',
    authDomain: 'masariweb.firebaseapp.com',
    storageBucket: 'masariweb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsFdztzneAdSMq9aEzwy0seWfaa8fSuy4',
    appId: '1:885423978672:android:9ce87c2630850278aca375',
    messagingSenderId: '885423978672',
    projectId: 'masariweb',
    storageBucket: 'masariweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHVIbd5GDo7VV3rIsM2OGPCyNmkq19Bqw',
    appId: '1:885423978672:ios:db6eb5083d16c2eaaca375',
    messagingSenderId: '885423978672',
    projectId: 'masariweb',
    storageBucket: 'masariweb.firebasestorage.app',
    iosBundleId: 'com.example.masariMasari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHVIbd5GDo7VV3rIsM2OGPCyNmkq19Bqw',
    appId: '1:885423978672:ios:db6eb5083d16c2eaaca375',
    messagingSenderId: '885423978672',
    projectId: 'masariweb',
    storageBucket: 'masariweb.firebasestorage.app',
    iosBundleId: 'com.example.masariMasari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzlDBkf7szFMDP9RoGOjwhKEUCKYmwDlQ',
    appId: '1:885423978672:web:3daf9831c55aae00aca375',
    messagingSenderId: '885423978672',
    projectId: 'masariweb',
    authDomain: 'masariweb.firebaseapp.com',
    storageBucket: 'masariweb.firebasestorage.app',
  );
}
