// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaAbdgFpZvyTkMNOu9EpgwGHWA-S0jT94',
    appId: '1:912489347164:web:91b7a5102465c729020e99',
    messagingSenderId: '912489347164',
    projectId: 'masari-81a47',
    authDomain: 'masari-81a47.firebaseapp.com',
    storageBucket: 'masari-81a47.firebasestorage.app',
    measurementId: 'G-Y5YJGGXP9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy0gK28zQ768H-eGz3GkuD5hq1rk4sOt8',
    appId: '1:912489347164:android:62a7c7b2d6d56643020e99',
    messagingSenderId: '912489347164',
    projectId: 'masari-81a47',
    storageBucket: 'masari-81a47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0I1yNt_iSNGlPI-yXbGhioZl6fWmH5o',
    appId: '1:912489347164:ios:9dbf0ed675343f16020e99',
    messagingSenderId: '912489347164',
    projectId: 'masari-81a47',
    storageBucket: 'masari-81a47.firebasestorage.app',
    iosBundleId: 'com.example.masari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0I1yNt_iSNGlPI-yXbGhioZl6fWmH5o',
    appId: '1:912489347164:ios:9dbf0ed675343f16020e99',
    messagingSenderId: '912489347164',
    projectId: 'masari-81a47',
    storageBucket: 'masari-81a47.firebasestorage.app',
    iosBundleId: 'com.example.masari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaAbdgFpZvyTkMNOu9EpgwGHWA-S0jT94',
    appId: '1:912489347164:web:a85535ec90fc7545020e99',
    messagingSenderId: '912489347164',
    projectId: 'masari-81a47',
    authDomain: 'masari-81a47.firebaseapp.com',
    storageBucket: 'masari-81a47.firebasestorage.app',
    measurementId: 'G-87WG56PS5D',
  );
}
